You may erroneously expect list1 to be equal to [10] and list3 to match with [‘a’], thinking that the list
argument will initialize to its default value of [] every time there is a call to the extendList.

However, the flow is like that a new list gets created once **after the function is defined**. 
And the same getsreused whenever someone calls the extendList method without a list argument. 

This is because the calculation of expressions (in default arguments) occurs **at the time of function definition**, not during its invocation.

The list1 and list3 are hence operating on the same default list, whereas list2 is running on a separate object that it has created on its own (by passing an empty list as the value of the list parameter).

In [7]:
del extendList
def extendList(val, list=[]):
    list.append(val)
    return list

In [8]:
list1 = extendList(10)
print (f"list1 = {list1}")
list2 = extendList(123,[])
print (f"list2 = {list2}")
list3 = extendList('a')
print (f"list3 = {list3}")

list1 = [10]
list2 = [123]
list3 = [10, 'a']

In [9]:
print (f"list1 = {list1}")
print (f"list2 = {list2}")
print (f"list3 = {list3}")

list1 = [10, 'a']
list2 = [123]
list3 = [10, 'a']

In [18]:
import sys
a = 0
b = 0
print(f"id(a): {id(a)}   size: {sys.getsizeof(a)}")
print(f"id(b): {id(b)}")
print(f"a is b: {a is b}")  # True, due to object caching for small integers
a = 256
b = 256
print(f"id(a): {id(a)}")
print(f"id(b): {id(b)}")
print(f"a is b: {a is b}")  # True, due to object caching for small integers

c = {}
d = {}
print(f"id(c): {id(c)}")
print(f"id(d): {id(d)}")
print(f"c is d: {c is d}")  # False, dictionaries are mutable and not cached

a = 257
b = 257
print(f"id(a): {id(a)}")
print(f"id(b): {id(b)}")
print(f"a is b: {a is b}")  # True, due to object caching for small integers

id(a): 110222590017992   size: 28
id(b): 110222590017992
a is b: True
id(a): 110222590026184
id(b): 110222590026184
a is b: True
id(c): 131896300526208
id(d): 131896300403584
c is d: False
id(a): 131896301744016
id(b): 131896301745776
a is b: False

## Closure

Closures are functions that "remember" variables from their enclosing scope, even after that scope has finished executing.

In [22]:
def make_multiplier(n):
    print(f" n is: {n}")
    def multiply(x):
        print(f"x: is {x} n is: {n}")
        return x * n
    return multiply

In [23]:
    
times_3 = make_multiplier(3)

 n is: 3

In [24]:
times_3(10)  # 30

x: is 10 n is: 3

30

In [28]:
def create_handler(prefix):
    def handler(event):
        print(f"{prefix}: {event}")
    return handler

In [29]:
error_handler = create_handler("ERROR")
warning_handler = create_handler("WARNING")
error_handler("File not found")  # ERROR: File not found
warning_handler("File not found")  # ERROR: File not found

ERROR: File not found
WARNING: File not found

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [23]:
import numpy as np
import pandas as pd
#
dtype: int64
 pd.Series([-1,2,3]).clip(np.array(0))
pd.Series([-1,2,3]).clip(0)

0    0
1    2
2    3
dtype: int64

In [16]:
a

0   -1
1    2
2    3
dtype: int64

In [21]:
a.clip(lower=0)
a.clip(np.array(0))
## .clip(lower=np.array(0))

TypeError: len() of unsized object

In [8]:
data = {"col_0": [9, -3, 0, -1, 5], "col_1": [-2, -7, 6, 8, -5]}
df = pd.DataFrame(data)
df

   col_0  col_1
0      9     -2
1     -3     -7
2      0      6
3     -1      8
4      5     -5

In [10]:
df.clip(lower = [-2, -1], upper=[4, 5])

   col_0  col_1
0      4     -1
1     -2     -1
2      0      5
3     -1      5
4      4     -1

In [15]:
ar = np.array(0)
ar.shape

()

In [ ]:
df.clip(lower = na )